from homeassistant.exceptions import HomeAssistantError


class ServiceError(HomeAssistantError):
    pass
